require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'MapPadding' do
  config = use_native_modules!

  # React Native
  use_react_native!(:path => config["reactNativePath"])

  # Mapbox
  $ReactNativeMapboxGLIOSVersion = '6.3.0' # '6.2.1' works

  pre_install do |installer|
    # Mapbox
    $RNMBGL.pre_install(installer)
  end

  post_install do |installer|
    # Mapbox
    $RNMBGL.post_install(installer)

    # Fixes issue where on ARM-based Macs, Xcode builds targeted for the Simulator
    # fail because the arm64 architecture is unsupported. 'Debug' corresponds to
    # the configuration set in Xcode > [Main project] > Info tab > Configurations.
    installer.pods_project.build_configurations.each do |config|
      if config.name == 'Debug'
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
    end
  end
end